# Generated by Django 4.2.5 on 2023-09-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0002_alter_form_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventquestion",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventquestion",
            name="event",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="options",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="statusquestion",
            name="option_0",
            field=models.CharField(blank=True, default="Off", max_length=10),
        ),
        migrations.AlterField(
            model_name="statusquestion",
            name="option_1",
            field=models.CharField(blank=True, default="On", max_length=10),
        ),
    ]
