# Generated by Django 4.2.5 on 2023-09-26 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0003_alter_question_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="options",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="multiplechoiceresponse",
            name="choice",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="statusresponse",
            name="status",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="symptomscoreresponse",
            name="score",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="textresponse",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
