# Generated by Django 4.2.5 on 2023-09-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0005_alter_statusquestion_option_0_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventquestion",
            name="date",
        ),
        migrations.AddField(
            model_name="formresponse",
            name="response_event",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="formresponse",
            name="response_event_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formresponse",
            name="response_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
