# Generated by Django 4.2.5 on 2023-09-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinician",
            name="patients",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="clinicians", to="authuser.patient"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
